### ISSUE TITLE
Todo convolutional autoencoder

### ISSUE THREAD

**Issue by DraTeots** [DraTeots/eic_ai_pid#2]
1. [ ] play with kernel_size
2. [ ] play with optimizer and error function, try mean_squared_error 
3. [ ] depth of convolutional layers
4. [ ] output layer (do we need Conv2D at all? 3x3 or 1x1 kernel?)
